# EXEMPLE DE DOCKER-COMPOSE.YAML (NON FONCTIONNEL POUR LE MOMENT)

services:
  postgres:
    image: postgres:latest # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_USER: user # Set the PostgreSQL user
      POSTGRES_PASSWORD: password # Set the PostgreSQL password
      POSTGRES_DB: mydatabase # Set the PostgreSQL database name
    ports:
      - "5432:5432" # Map port 5432 in the container to port 5432 on the host
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist PostgreSQL data

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/mydatabase
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username admin
        --password admin
        --firstname admin
        --lastname admin
        --role Admin
        --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8081:8080" # Map port 8080 in the container to port 8081 on the host
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/mydatabase
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/mydatabase
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler
volumes:
  pgdata: # Define a named volume for PostgreSQL data persistence